### ISSUE TITLE
Projets similaires

### ISSUE THREAD

**Issue by jpmckinney** [hooktstudios/seao-scraper#1]
Vous connaissez https://scraperwiki.com/scrapers/seao/ et https://scraperwiki.com/scrapers/seao_details/ ?

**Comment by j15e** [comment]
Merci de le porter à notre attention, on en a entendu parler mais ceux-ci ne semble plus fonctionner depuis que le site de SEAO a été modifié et notre scraper est fait dans une optique un peu différent je crois (republier les avis des nouveaux contrats selon des critères personnalisés principalement).

**Comment by jpmckinney** [comment]
Il fonctionne toujours - le 9 novembre un scraper a récupéré 2995 pages et créé 5988 documents, et l'autre a récupéré aujourd'hui 1404 pages pour 11919 documents. C'est juste la plateforme Scraperwiki qui ne fonctionne pas de temps en temps.
